imports:
    - { resource: parameters.yml }
#    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    #charset:         UTF-8
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        #strict_parameters: %kernel.debug%
    form:            false
    csrf_protection: false
    validation:      { enable_annotations: false }
    templating:      { engines: ['php'] } #assets_version: SomeVersionScheme
    #default_locale:  %locale%
    #session:
    #    auto_start:     false

# Twig Configuration
#twig:
#    debug:            %kernel.debug%
#    strict_variables: %kernel.debug%
